# Site settings
title: R. A. Lafferty
banner: Science Fiction, Magic, Philosophy & History
email: 
seo_description: Writer R.A. Lafferty was an original American treasure.  Praised by Neil Gaiman and Gene Wolfe, compared to Borges and Garcia Marquez, Lafferty eluded genres.
description: > # this means to ignore newlines until "baseurl:" 
  Inimitable Lafferty
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username:  
jira_url: 
github_username:  
github_wikipath: 
googlegroup: 

# Build settings
# markdown: RDiscount
markdown: kramdown
gems: [ jekyll-redirect-from ]
