# Site settings
title: R. A. Lafferty
email: 
description: > # this means to ignore newlines until "baseurl:" 
  Inimitable Lafferty
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username:  
jira_url: 
github_username:  
github_wikipath: 
googlegroup: 

# Build settings
# markdown: RDiscount
markdown: kramdown
